const { db } = require('../firebase.js')

const COLLECTION = 'officer'

async function createOfficer(data) {
  // Create a new document reference with an autogenerated ID but don't write yet
  const officerRef = db.collection(COLLECTION)

  const docRef = officerRef.doc()
  const UID = docRef.id
  // Include the generated UID in the document body before saving
  const dataWithUID = { UID, ...data }
  
  await docRef.set(dataWithUID)
  return dataWithUID
}

module.exports = {
  createOfficer
}