const { db } = require('../firebase.js')
const { convertOfficerDates, validateOfficerData } = require('./helpers/validators.js')

const COLLECTION = 'officer'

async function createOfficer(data) {
  // validate input shape before writing to Firestore
  validateOfficerData(data)

  // convert joinDate and role dates to Firestore Timestamps
  const dataConverted = convertOfficerDates(data)

  // Create a new document reference with an autogenerated ID but don't write yet
  const officerRef = db.collection(COLLECTION)

  const docRef = officerRef.doc()
  const UID = docRef.id
  // Include the generated UID in the document body before saving
  const dataWithUID = { UID, ...dataConverted }

  await docRef.set(dataWithUID)
  return dataWithUID
}

module.exports = {
  createOfficer
}